import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";
import { UserProvider } from "@/context/userContext";

const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "BRR Dashboard",
  description: "Generated by BRR Dashboard",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {

  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <UserProvider>
          <Navbar />
          <main className="max-w-6xl mx-auto p-4">{children}</main>
        </UserProvider>
      </body>
    </html>
  );
}
